version: "3.8"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
#    command: bash -c "psql -U ${DB_USER} ${DB_NAME} <<EOF CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; EOF"
  api:
    build: api
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/api
    command: go run main.go -b 0.0.0.0
  web:
    build: web
    ports:
      - "3001:3001"
    command: npm start

volumes:
  postgres-db: